### ISSUE TITLE
Server crushed ... with no dataBase reachability

### ISSUE THREAD

**Issue by ibram-reda** [AbanoubReda1/Project#1]
after cloning the app try to login with fake password the server crashed with `Login` function in student controller
### what i did (case scenario)

1.  clone you repo in my pc
2. run the application
3. click in login link
4. enter email as **abanoubreda68@gmail.com** and passowerd as **56645456dsf**
5. click create button (you should rename it to submit or login !!)
6. BOOOoom server crushed !! as following

![Capture](https://user-images.githubusercontent.com/37075700/76673172-43d3fa00-65ab-11ea-813b-a3510cf06a22.PNG)

i hav foun this line in the end of exaption body which mean >> server can not reach to database
```
Inner Exception 1:
SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

```
## solutions 
First of all you need to handle this exception even if the server can not found database it it must never crushed !! my suggestion is using try and catch  block like this
```
try
{
    v = dc.Students.Where(a => a.StudentEmail == login.StudentEmail).FirstOrDefault();
}
catch(Exception ee)
{
    // TO DO Handle this Exiption 
    // you can tell user to try in another time 
   
}

``` 

second of all you need to tell me how to clone the database structure of your project 😄 

**full exeption message**

```
System.Data.Entity.Core.EntityException
  HResult=0x80131501
  Message=The underlying provider failed on Open.
  Source=EntityFramework
  StackTrace:
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__1[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at StudentService.Controllers.StudentController.IsExsist(String email) in C:\Users\abram\source\repos\abanoubProject\Project\StudentService\StudentService\Controllers\StudentController.cs:line 185
   at StudentService.Controllers.StudentController.Registration(Student student) in C:\Users\abram\source\repos\abanoubProject\Project\StudentService\StudentService\Controllers\StudentController.cs:line 33
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()

Inner Exception 1:
SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)


```

**Comment by ibram-reda** [comment]
you need to provaid a way to clone your dataBase for other devolper ❗️ 

for example see the [Granite House project](https://github.com/bhrugen/GraniteHouse) (which you give it to me )it work fine 👍  
> only clone the project and project contain the database structure inside it with Data folder (which include dataMegrations) and when i run it Visual studio automaticlly re-build the data base agin in my side 😳😍  

this project use code first techniqu so it easy to rebuilde it again  (and has my own copy of database) .....   

### read this articles
- [quistion on stackOverFlow : What is better for team working on DB](https://stackoverflow.com/questions/3324517/best-practices-team-working-with-database)

- [how to copy your dataBase (tables shema and data)](https://www.codeproject.com/Tips/664327/Copy-Table-Schema-and-Data-From-One-Database-to-An)

 you need to Provide database copy in this repo so i can take it .... google on how can devolper teams can work togather on deatbase
